openapi: 3.1.0
info:
  title: GPT License Auth
  version: "1.0.0"

servers:
  - url: https://kwjxtfyzerwynwqnbpjk.supabase.co/functions/v1

paths:
  /entitlement:
    get:
      operationId: checkEntitlement
      security:
        - oauth: []
      responses:
        "200":
          description: License entitlement status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntitlementResponse"

components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://kwjxtfyzerwynwqnbpjk.supabase.co/functions/v1/oauth-authorize
          tokenUrl: https://kwjxtfyzerwynwqnbpjk.supabase.co/functions/v1/oauth-token
          scopes: {}

  schemas:
    EntitlementResponse:
      type: object
      properties:
        valid:
          type: boolean
          example: true
        reason:
          type: string
          enum:             
            - no_token
            - no_active_license
            - expired_license
          example: expired_license   
