openapi: 3.1.1
info:
  title: Loopyti Image Actions
  version: "1.0.0"
servers:
  - url: https://raw.githubusercontent.com/loopyti/gpt-test/main/API
paths:
  /postprocessImages:
    post:
      operationId: postprocessImages
      summary: Postprocess PNG images (resize, add metadata, export)
      requestBody:
        description: Image processing options
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                resize:
                  type: boolean
                  default: true
                dpi:
                  type: integer
                  default: 300
      responses:
        "200":
          description: Processed image result
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  download_url:
                    type: string
